### PR TITLE
Revert limit on the length of a non-GlobalValue name

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/llvmdev-feedstock/issues/68

Applies a patch to LLVM needed by Numba.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
It seems the aarch64 and ppc64le builds timeout. Is this expected?

**Comment by isuruf** [comment]
Yes, can you disable them by removing them from conda-forge.yml?

**Comment by jakirkham** [comment]
Thanks for the clarification @isuruf.

Wasn't sure what the syntax was for disabling them in `conda-forge.yml`. So added them to the `skip` in `meta.yaml`, which seemed to work.

**Comment by jakirkham** [comment]
@mariusvniekerk, would you be able to build the ARM and POWER packages for this? They will be needed for a new version of Numba.

**Pull request merged**
