### PR TITLE
10.0.0 with fixedup svml patch

### PR DESCRIPTION
**Pull request by timsnyder**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #84 

I'm not a maintainer here yet and couldn't push to the autotick bot branch.  Opening new PR to supercede #84 using the autotick bot's branch

### CODE REVIEW

**Comment by timsnyder** [comment]
@conda-forge-admin, please rerender

**Comment by timsnyder** [comment]
oops.  I understand how to fix the duplicate enum value error that we're hitting.  Will push a fix to the SVML patch to fix that.

**Comment by timsnyder** [comment]
After fixing the trivial enum duplicate, the next compile error is a bit more involved.  The new file `lib/Transforms/Utils/InjectTLIMappings.cpp` expects to get an unmangled function name back from `TargetLibraryInfoImpl::getVectorizedFunction()`.  The patch is a little wonky in that it will return a mangled name if the function comes from SVML but the name won't be mangled if it comes from something else.  I need to rework that function (and all of the callers that expect a mangled SVML name) to consistently return an unmangled function name so that the new code from 10.0.0 will work correctly.  

Might take me a day to two to peel this onion.

**Comment by pitrou** [comment]
While we are at it, could you please remove me (pitrou) from maintainers? Thanks in advance :-)

**Comment by timsnyder** [comment]
> While we are at it, could you please remove me (pitrou) from maintainers? Thanks in advance :-)

@pitrou, Done!

**Comment by timsnyder** [comment]
Well, I pushed my updated patch before the tests were done running locally.  I see the failure of `Transforms/Util/add-TLI-mappings.ll` locally on osx that was also observed [in the CI for linux](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=138409&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=ec8d466d-e3b4-5115-4f06-222398f91e6c&l=15491).

I understand [the failure](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=138409&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=ec8d466d-e3b4-5115-4f06-222398f91e6c&l=15425).  The test expects the munged name to not have the extra `_ha` suffix that our patch adds to the munged name.  I need to dig a bit deeper to understand whether this is hardcoded 'golden' test output that needs to be updated or if the slight change in name munging will really break something.

**Comment by timsnyder** [comment]
I've read back through the background for the SVML patch `recipe/patches/intel-D47188-svml-VF.patch` and took a step back to confirm that `recipe/numba-3016.ll` will still fail on unpatched 10.0.0.

**Comment by isuruf** [comment]
@conda-forge/numba, please have a look. Otherwise we'll have to drop this patch. I understand that this patch is needed for numba.

**Pull request merged**
