### PR TITLE
Fix LLJIT ignoring the CodeModel setting

### PR DESCRIPTION
**Pull request by bluescarni**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bluescarni** [comment]
@conda-forge/llvmdev This PR adds a small patch for a bug (fixed in LLVM 19) where LLJIT would ignore the CodeModel setting specified by the user, leading to compilation failures for large JIT compiled modules.

The issue was originally reported here:

https://github.com/llvm/llvm-project/issues/88115

Here is the PR with the fix:

https://github.com/llvm/llvm-project/pull/90599

**Comment by h-vetinari** [comment]
You did everything right with the rerender, but there's an unsolved issue with some components having been removed in the GHA images, which we need to reinstate here. If this situation persists, I guess we'll have to fix this in smithy at some point... In the meantime, I've just fixed it by hand.

**Review by h-vetinari — APPROVED** [review]

**Comment by bluescarni** [comment]
@conda-forge/llvmdev is this ready to be merged?

**Comment by h-vetinari** [comment]
Yeah, I was just waiting a little in case someone else has an opinion.

**Comment by h-vetinari** [comment]
Thanks!

**Pull request merged**
