### PR TITLE
Build shared libraries as well

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by mingwandroid** [comment]
Do you want to use these for the compilers too? That could be awesome, currently installing clang on macOS takes ages since we statically link them (and bundle all the static libs).

**Comment by isuruf** [comment]
Sure. rebuilding `clangdev` using this package would be enough.

**Comment by isuruf** [comment]
I'm going to merge this as it's backwards compatible and will work on 8.0.1

**Pull request merged**
