### PR TITLE
Start building LLVM with support for the experimental WebAssembly target

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/llvmdev-feedstock/issues/41

Start building the experimental WebAssembly target. This allows LLVM to be used to compiler C/C++ codes to WebAssembly. Not sure the viability of Fortran with Flang ATM, but that may also be possible.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
Had to switch to CircleCI for the macOS builds as the Travis CI builds timed out in the linking stage.

ref: https://travis-ci.org/conda-forge/llvmdev-feedstock/builds/412780833

**Comment by jakirkham** [comment]
Friendly nudge 😉

**Comment by inducer** [comment]
LGTM

**Comment by jakirkham** [comment]
Thanks for taking a look. Will submit a PR for `clangdev` after this build completes.

**Comment by jakirkham** [comment]
Unfortunately seems the AppVeyor build on `master` is getting cutoff before completion. Weird as it completed well within the time limit in the PR. 😕 Have raised upstream issue ( https://github.com/appveyor/ci/issues/2555 ).

**Comment by jakirkham** [comment]
Alright [second build]( https://ci.appveyor.com/project/conda-forge/llvmdev-feedstock/build/1.0.128 ) narrowly made it at 1hr28min.

**Pull request merged**
