### PR TITLE
Apply upstream aarch64 consecutive register fix (12.x)

### PR DESCRIPTION
**Pull request by jakirkham**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Same as PR ( https://github.com/conda-forge/llvmdev-feedstock/pull/164 ), but for 12.x. The fix shows up in 13.0.0 so shouldn't be needed for later versions.

xref: https://reviews.llvm.org/D104123

### CODE REVIEW

**Review by isuruf — CHANGES_REQUESTED** [review]
This is an ABI breakage. See the last comment in https://bugs.llvm.org/show_bug.cgi?id=46996

**Comment by jakirkham** [comment]
Does this apply to PR ( https://github.com/conda-forge/llvmdev-feedstock/pull/164 ) as well? If so, we may need to drop `aarch64` builds of Numba as they hang in the test suite without this patch.

**Comment by isuruf** [comment]
Yes, it does. You can easily fix the ABI breakage by keeping both the old signature and the new signature.

**Comment by jakirkham** [comment]
For clarity PR ( https://github.com/conda-forge/llvmdev-feedstock/pull/164 ) is for 11.x (not 12.x)

**Comment by gmarkall** [comment]
Numba skipped LLVM 12 and went straight to 14 - should this be closed?

**Comment by h-vetinari** [comment]
> Numba skipped LLVM 12 and went straight to 14 - should this be closed?

yup, I think so

**Pull request closed without merging**
