### PR TITLE
Update SVML patch to llvm11

### PR DESCRIPTION
**Pull request by Hardcode84**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Update SVML patch to llvm11, also incorporates fixes for SVML calling conventions issues found by Numba and some code refactoring.

### CODE REVIEW

**Comment by isuruf** [comment]
Thanks @Hardcode84, is this on top of 11.0.0.rc2 ?

**Comment by Hardcode84** [comment]
Hm, let me recheck

**Comment by Hardcode84** [comment]
Hm, I will probably update to current `release/11.x` HEAD (as it quite ahead of rc2) and recheck after llvm11 final is out. It this ok?

**Comment by isuruf** [comment]
Yes. Thanks for doing this. I'll try it after 11.0.0 final is out.

**Comment by Hardcode84** [comment]
updated numba test

**Pull request closed without merging**
