### PR TITLE
Add cling patches for cling packaging

### LINKED ISSUE #6: Co-maintainership for SylvainCorlay
Hey @SylvainCorlay, want to co-maintain `llvmdev` and `clangdev`?

### PR DESCRIPTION
**Pull request by SylvainCorlay**
The goal is to package the cling C++ interpreter from CERN on conda-forge, which requires applying patches to llvm and clang.

This creates a new flavor for this package, only used when the cling  [feature](http://conda.pydata.org/docs/building/meta-yaml.html#id1) is active, in which a few patches are applied on the llvm source tree.

Instead of squashing the patches together, I apply them separately so that it is easy to track when some are added or removed.

The `clang` package will also use the same feature (https://github.com/conda-forge/clangdev-feedstock/pull/1).

The `cling` package is the one that will provide the `track_feature` statement.

Fixes #6 

@msarahan is this the right way to go with this?

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Ping @minrk you might be interested in this.

**Comment by SylvainCorlay** [comment]
The discussion is in https://github.com/conda-forge/clangdev-feedstock/pull/1

**Comment by inducer** [comment]
Would you think it is possible to keep these patches in a `for-cling` (or some-such) subfolder?

**Comment by SylvainCorlay** [comment]
OK, I moved all the patches to a `cling-patches` directory, which is also the name of the llvm branch holding the patches and now the name of the conda feature.

**Comment by SylvainCorlay** [comment]
Rebased upon 3.9.1 release.

**Comment by SylvainCorlay** [comment]
Since conda-forge now has a Python 3.6 flavor, we should probably change

`skip: true  # [(unix and py3k) or (win and py<35)]`

into

`skip: true  # [(unix and py3k) or (win and py<36)]`

to avoid unnecessary builds on windows?

**Comment by inducer** [comment]
Agreed.

**Comment by SylvainCorlay** [comment]
Note: conda feature names cannot have dashes so it is going to be "cling".

**Comment by jakirkham** [comment]
> The `cling` package is the one that will provide the `track_feature` statement.

FYI have tried this myself before with other things and it was quite painful in the end. The recommended way of handling features is having an independent metapackage, which provides the feature. We used this with `blas` here in `conda-forge` and it was quite successful. I say this not to be critical, but to hopefully avoid long term suffering. Though maybe @mcg1969 could weigh in and provide better guidance yet.

**Comment by mcg1969** [comment]
As long as 1) the `cling` package is the only one providing the feature, and 2) the `cling` package _always_ provides the feature---that is to say, there aren't versions of this package that omit it---then I think it's safe to include it there.

**Comment by SylvainCorlay** [comment]
OK. I have not problem with creating a meta package for the feature.

**Comment by SylvainCorlay** [comment]
I submitted a `cling-patches` meta package to the staged recipes which tracks the `cling` feature.

**Comment by jakirkham** [comment]
Would it make sense to have one feedstock for metapackages of all variants of patches that can be applied to `clang`?

**Comment by SylvainCorlay** [comment]
> Would it make sense to have one feedstock for metapackages of all variants of patches that can be applied to clang?

Is there any you are already one other that you can think of?

Can you think of a feature that would apply to clang or llvm and some other unrelated thing?

**Comment by SylvainCorlay** [comment]
I am confused by the windows-only error:

```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - llvmdev 3.9.1 vc14_cling_1 -> feature:cling
```

which only occurs with the cling feature, and one of the items of thebuild matrix in the first commit.

**Comment by jakirkham** [comment]
I think Julia has some patches they apply to `llvm`. Maybe @tkelman can elaborate.

**Comment by SylvainCorlay** [comment]
> I think Julia has some patches they apply to llvm. Maybe @tkelman can elaborate.

Would this have a consequence on the package name? i.e. are you thinking of one feedstock for all the packages?

**Comment by jakirkham** [comment]
Just thinking it would be nice to avoid a proliferation of patch packages. Also should help avoid conflicts and maybe systemize it a bit. What do you think?

**Comment by SylvainCorlay** [comment]
> Just thinking it would be nice to avoid a proliferation of patch packages. Also should help avoid conflicts and maybe systemize it a bit. What do you think?

I was just wondering if this would be a good idea for patch features that have overlapping yet different sets of impacted packages - but I don't have a strong opinion on this.

**Comment by tkelman** [comment]
We try to upstream almost all of our patches, which cling should really be doing too. Most of the ones we carry are backported bug fixes or performance improvements. Until someone wants to build Julia against conda-forge's version of llvm I don't really care what you're doing here. I pretty strongly advocated that llvm packages should be maintained for separate versions in parallel, but that appears not to have happened yet. Every package repository eventually gets there once you have enough things depending on llvm though.

**Comment by SylvainCorlay** [comment]
It is my understanding that cling folks are working on contributing their patches upstream too.

So this depends on https://github.com/conda-forge/staged-recipes/pull/2301 getting in (the meta package for the cling feature).

**Comment by inducer** [comment]
(Marked WIP pending `cling-patches` merge.)

**Comment by SylvainCorlay** [comment]
Does someone of the core team make sense of the windows only unsatisfiable conda requirement error

```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - llvmdev 3.9.1 vc14_cling_1 -> feature:cling
```

**Comment by SylvainCorlay** [comment]
Is there a chance to get https://github.com/conda-forge/staged-recipes/pull/2301 and this in before the huge os x backlog start again tomorrow?

**Comment by SylvainCorlay** [comment]
@inducer this is good to go. Just waiting for the OS X build. (which works as tested locally anyways).

**Comment by SylvainCorlay** [comment]
I can't believe the travis ci build is still pending. This has been in the queue for 30 hours. The sad part is that we will get back in the queue when it is merged before I can get t0 clang, and then to cling.

**Pull request merged**
