### PR TITLE
Update to 3.9, rerender

### PR DESCRIPTION
**Pull request by inducer**

### CODE REVIEW

**Comment by inducer** [comment]
@pitrou, looks like OProfile has bitrotted in llvm 3.9 (see the circle build log). You mentioned [an interest in having it enabled](https://github.com/conda-forge/staged-recipes/pull/1482#issuecomment-244785176) when this first got put together. I don't know much about that code.

Huh: Just saw [this mailing list message](http://lists.llvm.org/pipermail/llvm-dev/2016-September/104844.html) from you. Did you learn anything since then?

**Comment by pitrou** [comment]
Well, I guess OProfile support can be ditched, then. I haven't heard back about it.

**Comment by inducer** [comment]
Removed. Thanks for getting back to me so quickly.

**Comment by inducer** [comment]
FWIW, we can easily revert that if the support comes back.

**Pull request merged**
