### PR TITLE
Set LLVM to build default (all) targets (was PR-18)

### PR DESCRIPTION
**Pull request by pearu**
This is updated PR #18 that uses azure provider in `conda-forge.yml`.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by pearu** [comment]
The linux azure build fails with
```
2019-01-31T23:32:46.0409433Z Source and build intermediates have been left in /home/conda/feedstock_root/build_artifacts.
2019-01-31T23:32:46.0409667Z There are currently 1 accumulated.
2019-01-31T23:32:46.0409901Z To remove them, you can run the ```conda build purge``` command
2019-01-31T23:32:47.1010299Z + [[ True != \F\a\l\s\e ]]
2019-01-31T23:32:47.1011117Z + upload_package /home/conda/feedstock_root /home/conda/recipe_root /home/conda/feedstock_root/.ci_support/linux_.yaml
2019-01-31T23:32:48.3111164Z No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
2019-01-31T23:32:48.3361384Z Adding in variants from internal_defaults
2019-01-31T23:32:48.3361484Z Adding in variants from /home/conda/feedstock_root/.ci_support/linux_.yaml
2019-01-31T23:32:48.3970213Z Attempting to finalize metadata for llvmdev
2019-01-31T23:33:11.4130072Z Collecting package metadata: ...working... done
2019-01-31T23:33:12.4380756Z Solving environment: ...working... done
2019-01-31T23:33:15.1245933Z Collecting package metadata: ...working... done
2019-01-31T23:33:15.5579742Z Solving environment: ...working... done
2019-01-31T23:33:18.2082684Z Collecting package metadata: ...working... done
2019-01-31T23:33:18.6382422Z Solving environment: ...working... done
2019-01-31T23:33:18.6434016Z Adding .* to spec 'llvm-meta 7.0.1' to ensure satisfiability.  Please consider putting {{ var_name }}.* or some relational operator (>/</>=/<=) on this spec in meta.yaml, or if req is also a build req, using {{ pin_compatible() }} jinja2 function instead.  See https://conda.io/docs/user-guide/tasks/build-packages/variants.html#pinning-at-the-variant-level
2019-01-31T23:33:20.8072907Z Traceback (most recent call last):
2019-01-31T23:33:20.8073046Z   File "/opt/conda/bin/upload_package", line 11, in <module>
2019-01-31T23:33:20.8079025Z     sys.exit(upload_package())
2019-01-31T23:33:20.8082692Z   File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 764, in __call__
2019-01-31T23:33:20.8088162Z     return self.main(*args, **kwargs)
2019-01-31T23:33:20.8088646Z   File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 717, in main
2019-01-31T23:33:20.8092582Z     rv = self.invoke(ctx)
2019-01-31T23:33:20.8101448Z   File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 956, in invoke
2019-01-31T23:33:20.8103377Z     return ctx.invoke(self.callback, **ctx.params)
2019-01-31T23:33:20.8111583Z   File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 555, in invoke
2019-01-31T23:33:20.8111970Z     return callback(*args, **kwargs)
2019-01-31T23:33:20.8112333Z   File "/opt/conda/lib/python3.6/site-packages/conda_forge_ci_setup/build_utils.py", line 82, in upload_package
2019-01-31T23:33:20.8114745Z     upload_or_check(recipe_root, owner, channel, [config_file])
2019-01-31T23:33:20.8115223Z   File "/opt/conda/lib/python3.6/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 135, in upload_or_check
2019-01-31T23:33:20.8115329Z     upload(token_fn, path, owner, channel)
2019-01-31T23:33:20.8115982Z   File "/opt/conda/lib/python3.6/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 65, in upload
2019-01-31T23:33:20.8116591Z     env=os.environ)
2019-01-31T23:33:20.8116667Z   File "/opt/conda/lib/python3.6/subprocess.py", line 311, in check_call
2019-01-31T23:33:20.8127390Z     raise CalledProcessError(retcode, cmd)
2019-01-31T23:33:20.8128466Z subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', '/tmp/tmp43dsvn_v/binstar.token', 'upload', '/home/conda/feedstock_root/build_artifacts/linux-64/llvmdev-7.0.1-h6bb024c_1002.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1.
2019-01-31T23:33:22.9664528Z ##[error]Bash exited with code '1'.
2019-01-31T23:33:22.9677331Z ##[section]Finishing: Run docker build
```
Can anyone recognize the reason and propose a fix? Would the failure be due to
```
Adding .* to spec 'llvm-meta 7.0.1' to ensure satisfiability.  Please consider putting {{ var_name }}.* or some relational operator (>/</>=/<=) on this spec in meta.yaml, or if req is also a build req, using {{ pin_compatible() }} jinja2 function instead
```
?

**Comment by xmnlab** [comment]
@conda-forge/llvmdev-feedstock any idea about this?

**Comment by pearu** [comment]
@SylvainCorlay @isuruf @jakirkham , please review.

**Comment by xmnlab** [comment]
hey @conda-forge/llvmdev, any feedback?

**Comment by pitrou** [comment]
The risk here is that downstream users may get larger link sizes if not careful. One such example is `llvmlite`. @sklam @stuartarchibald do you want to comment?

**Comment by pearu** [comment]
The size of `libllvmlite.so` is:
- about 40MB with targets WebAssembly X86
- about 60MB with all default targets (AArch64 AMDGPU ARM BPF Hexagon Lanai Mips MSP430 NVPTX PowerPC Sparc SystemZ X86 XCore WebAssembly)

I would be fine with adding NVPTX target only. Many projects using GPU devices for computations would benefit from that.

**Comment by pearu** [comment]
Let me also add that there are really no good alternatives to not providing the default targets in llvmdev shipped by conda-forge. There is a real need for it and options like
- building llvmdev from source
- creating a new conda project, say, llvmdev-all
- use system provided llvmdev (in Ubuntu llvmdev has all targets built in, for instance)
- etc

sound really bad for various reasons.

**Comment by stuartarchibald** [comment]
I'm wondering if `llvm-config` output can be leveraged to provide selective linking of components. For example, I have a ROC (AMDGPU) enabled LLVM locally and it provides the following (note the `amdgpu*` components):
```
$ llvm-config --targets-built
AMDGPU X86

$ llvm-config --components
aggressiveinstcombine all all-targets amdgpu amdgpuasmparser amdgpuasmprinter amdgpucodegen 
amdgpudesc amdgpudisassembler amdgpuinfo amdgpuutils analysis asmparser asmprinter 
binaryformat bitreader bitwriter codegen core coroutines coverage debuginfocodeview debuginfodwarf 
debuginfomsf debuginfopdb demangle dlltooldriver engine executionengine fuzzmutate globalisel 
instcombine instrumentation interpreter ipo irreader libdriver lineeditor linker lto mc mcdisassembler 
mcjit mcparser mirparser native nativecodegen objcarcopts object objectyaml option orcjit passes 
profiledata runtimedyld scalaropts selectiondag support symbolize tablegen target transformutils 
vectorize windowsmanifest x86 x86asmparser x86asmprinter x86codegen x86desc x86disassembler 
x86info x86utils
```
the `llvm-config` flags optionally take a list of components to limit the output in relation to the flag, for example:
```
$llvm-config --libs x86 mcjit engine passes
-lLLVMPasses -lLLVMipo -lLLVMInstrumentation -lLLVMVectorize -lLLVMLinker -lLLVMIRReader 
-lLLVMAsmParser -lLLVMMCJIT -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMX86Disassembler
 -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMGlobalISel -lLLVMSelectionDAG -lLLVMAsmPrinter 
-lLLVMCodeGen -lLLVMTarget -lLLVMScalarOpts -lLLVMInstCombine -lLLVMAggressiveInstCombine 
-lLLVMTransformUtils -lLLVMBitWriter -lLLVMAnalysis -lLLVMProfileData -lLLVMX86Desc 
-lLLVMObject -lLLVMMCParser -lLLVMBitReader -lLLVMMCDisassembler -lLLVMX86Info 
-lLLVMX86AsmPrinter -lLLVMMC -lLLVMDebugInfoCodeView -lLLVMDebugInfoMSF -lLLVMX86Utils 
-lLLVMCore -lLLVMBinaryFormat -lLLVMSupport -lLLVMDemangle

```
so I'd hope it's possible to perhaps patch `llvmlite` to use a restricted `x86` target specific subset?

**Comment by pitrou** [comment]
Ideally `llvm-config` works for that indeed. I'm not sure we're using that feature in `llvmlite`, AFAIR some components may have been missing, or perhaps on the contrary too many components were included?

**Comment by stuartarchibald** [comment]
At present there's no such component masking https://github.com/numba/llvmlite/blob/d5fadccb003527b33682af1a6a009ed5619606a2/ffi/build.py#L121-L150 but it could/should probably be explored ahead of this change as keeping binary size down is important. I cannot see at present a reason for this to not work. The Numba stack's next release cycle window closes in a couple of weeks so perhaps such a change could be tested at the start of the next cycle to get maximum time to explore/fix, https://github.com/numba/llvmlite/issues/462 tracks.

**Comment by pearu** [comment]
@pitrou @stuartarchibald , for the background why I care about this issue: I am working on a project that aims at calling numba generated LLVM IR remotely. For instance, in a client program one can define a Python function that is processed by numba to produce a LLVM IR string. This string is sent to a server where the LLVM IR is compiled to machine code and executed as requested. The server does not have to be numba aware as there may exists other clients that may produce LLVM IR strings by other means (rather than numba).
For this to work, the llvmlite in client side must use a version of llvmdev that supports all the targets that the server has. For instance, one could launch CUDA kernels from a client (that does not have GPU devices in itself) in the GPU-enabled server remotely. Or in general, one could execute a client defined code on a server that has different architecture from the client machine.

Hence, it is important for this project that llvmlite would also use the llvmdev where all (or at least NVPTX) targets are enabled.

**Comment by isuruf** [comment]
Since we build all targets on windows and there weren't any complaints on binary size on windows, I'm guessing this is fine on unix too.

**Comment by jakirkham** [comment]
@pearu, can you please send a PR to `llvmlite` to bump the build number so it can be rebuilt with the new `llvmdev` (if you haven’t already :)?

**Comment by pearu** [comment]
@jakirkham , as I understand, approval of [llvmlite-feedstock PR 13](https://github.com/conda-forge/llvmlite-feedstock/pull/13) is needed to rebuild llvmlite with the new `llvmdev`.

**Pull request merged**
