### PR TITLE
Build llvm 14.0.0.rc1

### PR DESCRIPTION
**Pull request by h-vetinari**
After the release is before the release...

### CODE REVIEW

**Comment by h-vetinari** [comment]
This seems to be hitting https://github.com/llvm/llvm-project/issues/53281

**Comment by h-vetinari** [comment]
@conda-forge/llvmdev, this now builds everywhere (thanks for adding the workaround @xhochy and cleaning up the ninja-vs-make situation!).

Since this PR is only pushing to `llvm_rc`, I don't think there should be big concerns even if the details might not be perfect, but just for completeness: MSVC and MACOSX_SDK are being bumped in this PR.

**Comment by h-vetinari** [comment]
@isuruf @xhochy 
Just noticed that the CI didn't trigger upon merging. Could someone trigger/restart it please?

**Comment by xhochy** [comment]
Pushed an empty commit

**Comment by h-vetinari** [comment]
> Pushed an empty commit

OK thanks, I'll just do that then next time (where I have maintainer rights...

**Pull request merged**
