### PR TITLE
llvmdev v7.0.0 with rebased SVML

### PR DESCRIPTION
**Pull request by anton-malakhov**
Rebased SVML patch and merged it with a better fix for vectorization factor bug in Legalizer.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #46

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks for working on this Anton.

One thing we could try is [SSH-ing into a failed build]( https://circleci.com/docs/2.0/ssh-access-jobs/ ). We have to tell CircleCI that we want to run an SSH build and I think it has some time limit after which the VM expires, but this could be a good way to figure out what is going on there.

**Comment by anton-malakhov** [comment]
ok.. so, it is our patch after all.. one idea is that the compiler broke RVO when returning string class

**Comment by anton-malakhov** [comment]
@jakirkham It works finally!

**Comment by mingwandroid** [comment]
> one idea is that the compiler broke RVO when returning string class

Did this turn out not to be the case?

**Comment by anton-malakhov** [comment]
@mingwandroid No, though I'm not entirely sure how exactly it was broken because I haven't seen it in debugger, but it is about LLVM's string manipulation approach with their StringRef class which has implicit conversion from std::string and which doesn't really work. So, it's another artifact of merging two patches here, which is not as obvious as a merge conflict or a compilation error.

**Comment by anton-malakhov** [comment]
The second part of this merged patch is published as https://reviews.llvm.org/D53035

**Pull request merged**
