### PR TITLE
8.x rerender

### PR DESCRIPTION
**Pull request by xhochy**
…da-forge-pinning 2020.06.23.15.05.51

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
Why is this needed?

**Comment by xhochy** [comment]
We want to have a manual `aarch64` build of 8.0.1 for https://github.com/conda-forge/llvmlite-feedstock/pull/19

Instead of doing it with outdated scripts, I would prefer to have the scripts updates for the packages we have CI for and then do the manual build usimg just a rerender that includes scripts for running an `aarch64` build.

**Comment by isuruf** [comment]
Closing this as 8.x is no longer maintained.

**Comment by isuruf** [comment]
I don't know who created 8.x branch, but I deleted it as it's not maintained.

**Comment by jakirkham** [comment]
I created it last night as we need this for `llvmlite`.

Can you please add it back @isuruf? I don’t understand why it needs to be deleted.

**Pull request closed without merging**
