### PR TITLE
Add arch rebuild for 5.x

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Required for https://github.com/conda-forge/root-feedstock/pull/111

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Comment by chrisburr** [comment]
@conda-forge/llvmdev, ready for merging! This PR adds ARM/POWER for LLVM 5 which is required for https://github.com/conda-forge/root-feedstock/pull/111

**Review by isuruf — CHANGES_REQUESTED** [review]
There were changes needed to allow cross compiling. Those need to be backported here

**Comment by chrisburr** [comment]
@isuruf I guess those were the `build.sh` and `pass-through-qemu-ld-prefix.diff` changes in?

https://github.com/conda-forge/llvmdev-feedstock/pull/95/files#diff-44a73bcc045c193c3bd45da87994b03b

Or is there something else? If it's complex I might just disable POWER as I mostly care about ARM for now which is still being built natively.

**Comment by isuruf** [comment]
Yes, and the follow up PR https://github.com/conda-forge/llvmdev-feedstock/pull/99/

**Comment by isuruf** [comment]
`pass-through-qemu-ld-prefix.diff` is not strictly necessary

**Comment by chrisburr** [comment]
@isuruf I think I've backported everything that matters

**Comment by chrisburr** [comment]
@isuruf @conda-forge/llvmdev I think this is ready

**Comment by chrisburr** [comment]
Thanks @isuruf! 🍰

**Pull request merged**
