### PR TITLE
Update to LLVM 11.0.0

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes #100
Fixes #101
Fixes #104

### CODE REVIEW

**Comment by isuruf** [comment]
Intel SVML patch does not apply. cc @anton-malakhov, @Hardcode84

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
Pushed to `rc` branch

**Comment by isuruf** [comment]
@Hardcode84, the tests fail with,
```
2020-10-12T16:51:14.8754872Z + bin/opt -S -vector-library=SVML -mcpu=haswell -O3 /home/conda/recipe_root/numba-3016.ll
2020-10-12T16:51:14.8759163Z + bin/FileCheck /home/conda/recipe_root/numba-3016.ll
2020-10-12T16:51:14.9067105Z /home/conda/recipe_root/numba-3016.ll:9:14: error: CHECK-NOT: excluded string found in input
2020-10-12T16:51:15.5965394Z ; CHECK-NOT: __svml_sin8
2020-10-12T16:51:15.5967405Z              ^
2020-10-12T16:51:15.5967929Z <stdin>:8:228: note: found here
2020-10-12T16:51:15.5969930Z @llvm.compiler.used = appending global [3 x i8*] [i8* bitcast (<2 x double> (<2 x double>)* @__svml_sin2_ha to i8*), i8* bitcast (<4 x double> (<4 x double>)* @__svml_sin4_ha to i8*), i8* bitcast (<8 x double> (<8 x double>)* @__svml_sin8_ha to i8*)], section "llvm.metadata"
2020-10-12T16:51:15.5972031Z                                                                                                                                                                                                                                    ^~~~~~~~~~~
2020-10-12T16:51:15.5973211Z 
2020-10-12T16:51:15.5973654Z Input file: <stdin>
2020-10-12T16:51:15.5974828Z Check file: /home/conda/recipe_root/numba-3016.ll
2020-10-12T16:51:15.5975506Z 
2020-10-12T16:51:15.5976398Z -dump-input=help explains the following input dump.
2020-10-12T16:51:15.5977992Z 
2020-10-12T16:51:15.5978443Z Input was:
2020-10-12T16:51:15.5978954Z <<<<<<
2020-10-12T16:51:15.5979983Z        1: ; ModuleID = '/home/conda/recipe_root/numba-3016.ll'
2020-10-12T16:51:15.5980972Z        2: source_filename = "svml-3016.c"
2020-10-12T16:51:15.5982277Z        3: target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
2020-10-12T16:51:15.5983552Z        4: target triple = "x86_64-pc-linux-gnu"
2020-10-12T16:51:15.5984221Z        5: 
2020-10-12T16:51:15.5985002Z        6: @a = common dso_local local_unnamed_addr global [1024 x i32] zeroinitializer, align 16
2020-10-12T16:51:15.5986031Z        7: @b = common dso_local local_unnamed_addr global [1024 x i32] zeroinitializer, align 16
2020-10-12T16:51:15.5987913Z        8: @llvm.compiler.used = appending global [3 x i8*] [i8* bitcast (<2 x double> (<2 x double>)* @__svml_sin2_ha to i8*), i8* bitcast (<4 x double> (<4 x double>)* @__svml_sin4_ha to i8*), i8* bitcast (<8 x double> (<8 x double>)* @__svml_sin8_ha to i8*)], section "llvm.metadata"
2020-10-12T16:51:15.5990778Z not:9                                                                                                                                                                                                                                        !~~~~~~~~~~                                      error: no match expected
2020-10-12T16:51:15.5992630Z        9: 
2020-10-12T16:51:15.5993170Z       10: ; Function Attrs: nofree nounwind uwtable
2020-10-12T16:51:15.5993831Z       11: define dso_local void @foo() local_unnamed_addr #0 {
2020-10-12T16:51:15.5994546Z       12: vector.ph:
2020-10-12T16:51:15.5995185Z       13:  br label %vector.body
2020-10-12T16:51:15.5995748Z        .
2020-10-12T16:51:15.5996127Z        .
2020-10-12T16:51:15.5996587Z        .
2020-10-12T16:51:15.5996938Z >>>>>>
2020-10-12T16:51:15.5997277Z + exit 1
```

**Comment by Hardcode84** [comment]
Ok, I'll check

**Comment by isuruf** [comment]
Thanks @Hardcode84

**Pull request merged**
