### PR TITLE
Add patch for Windows

### PR DESCRIPTION
**Pull request by souravsingh**
Required for fixing the ``llvmlite`` recipe- https://github.com/conda-forge/staged-recipes/pull/4068

### CODE REVIEW

**Comment by inducer** [comment]
Looks like the Windows build is failing with that patch.

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
This needs a build number bump. Btw, wouldn't this break downstream packages expecting a dll?

**Comment by souravsingh** [comment]
The patch is required for ``llvmlite`` to work on Windows, which is a dependency for ``numba``. Should we wait until new release?

**Comment by jakirkham** [comment]
It would help if some numba devs could take a look. Also given @mingwandroid played a big role in the current Windows configuration, would be good to have his take as well.

cc @pitrou @sklam

**Comment by jakirkham** [comment]
I think I hear crickets. :) Any thoughts on this one? ;)

**Comment by pitrou** [comment]
For the record, I'm not actively maintaining llvmlite anymore :-)

**Comment by mingwandroid** [comment]
I can't really comment on LLVM on Windows since I've not touched it (yet). I have experience building it with GCC on Windows but that's not much use here.

**Comment by jakirkham** [comment]
Ah sorry for the ping @pitrou. Do you know who is?

**Comment by pitrou** [comment]
Perhaps @sklam or @stuartarchibald I'd say.

**Comment by isuruf** [comment]
@souravsingh, can you send this PR as a patch to @xoviat's repo for https://github.com/conda-forge/llvmdev-feedstock/pull/23 where there is a version update.

**Comment by xoviat** [comment]
I can pull these.

**Comment by jakirkham** [comment]
Would it be alright if we just merge this now? Especially if we are wanting to merge it anyways.

**Comment by isuruf** [comment]
@jakirkham, see https://github.com/conda-forge/llvmdev-feedstock/pull/21#issuecomment-336465520

**Comment by jakirkham** [comment]
If we are concerned about it breaking things, why do we want to accept it? Anyways I had the impression this was suppose to just be static libraries or am I confused?

**Comment by isuruf** [comment]
It will break things already built with the shared library because those downstream packages will be expecting a shared build. With a version update like 5.0.0, there are no downstream packages to worry about.

**Comment by jakirkham** [comment]
Ok. That's fine.

Though this package is suppose to be only static libraries right? If that is correct, arguably any packages that don't use static libraries are defective (just based on intent). The libraries do work fine though.

**Comment by jakirkham** [comment]
So did this actually land in a 4.0.x version?

**Comment by xoviat** [comment]
Nope. It's in 5.0.

**Comment by jakirkham** [comment]
Hmm...so we kind of need this in 4.0.x because of this problem with `llvmlite` ( https://github.com/conda-forge/staged-recipes/pull/4068#issuecomment-343695524 ). How would we like to do this?

**Comment by xoviat** [comment]
My suggestion is to branch off the 4.0 build and then backport the patch + a new build number.

**Comment by xoviat** [comment]
```
git checkout c1d1ab73bc3149ae221e4a39dad331d4ad1eb63e
git checkout -b maintenance/4.0.x
git push origin maintenance/4.0.x
```

**Comment by jakirkham** [comment]
Right. I'm aware of what needs to be done to create the PR. What I'm less clear on is how we go about resolving [this issue]( https://github.com/conda-forge/llvmdev-feedstock/pull/21#issuecomment-341830678 ).

**Comment by xoviat** [comment]
Do you have a windows build now for llvmlite? If it were me, I'd build HEAD for windows now (which appears to support LLVM 5), and then roll version parity into the next release. Otherwise, it appears that you'll need to create a new feature so that you don't break other's builds.

**Comment by jakirkham** [comment]
So that's not typically how we release things in conda-forge. We like upstream to give some indication that they intend to release by tagging it or something. There are certainly some exceptions like we may use patches if critical bugs crop up or if there are no final releases we might use and rc/dev release. However these are exceptions to the rule.

**Comment by xoviat** [comment]
Of course not. But at least for me, an "initial" release is different than subsequent releases, because at least initially, you may have patches that you need to push upstream. But I'm not in charge here, so you shouldn't listen to me. I'm just telling you what I think the options are.

**Pull request merged**
