### PR TITLE
Release 3.9.1

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Travis is green!

**Comment by SylvainCorlay** [comment]
Weird I still can't merge while I was added to the maintainer list.

**Comment by SylvainCorlay** [comment]
@inducer would you be ok merging this. The sequence of depebdent prs to get in for cling packaging is long and I would like to be able to iterate over the week end while travis usage is low.

**Comment by inducer** [comment]
Odd that you can't merge. Oh well, I've pushed the button.

**Comment by SylvainCorlay** [comment]
It might be done with a cron job that has not run yet.

**Comment by SylvainCorlay** [comment]
Thanks

**Comment by jakirkham** [comment]
It's done by a cron job on Travis CI. Not to mention it was broken recently. 😞 That said I think we fixed it. We just have to wait awhile until it starts (is queued).

Really we need to get that sort of thing to not run on Travis CI and not be a cron job. It is a real maintenance burden as it stands now. The long Travis CI queue just makes it more apparent. All it takes is one mess up in a recipe somewhere to grind the whole thing to a halt. So I have pushed for rewriting it as a webservice that listens to webhooks on each feedstock. I think at this point it is a matter of having the time to write it.

xref: https://github.com/conda-forge/conda-forge-webservices/issues/63

**Pull request merged**
