### PR TITLE
Re-enable zstd-support in cross-compilation

### PR DESCRIPTION
**Pull request by h-vetinari**
There were some issues with zstd in #163, let's try re-enabling it.

### CODE REVIEW

**Comment by h-vetinari** [comment]
I think there's a bootstrapping issue here. We'd need a native `llvm-config` for the cross-compilation builds, but we're only building that one in the same PR...

**Comment by isuruf** [comment]
No, that's incorrect. Please revert 0271056

**Comment by h-vetinari** [comment]
> No, that's incorrect. Please revert [0271056](https://github.com/conda-forge/llvmdev-feedstock/commit/0271056561107afbb76741b9c2fa8f88b5fa2933)

Done, thanks; I'd normally rebase out those garbage commits, but didn't want to touch yours if not necessary. So far, this PR was more exploratory than anything... :)

**Comment by isuruf** [comment]
Rebasing should be fine as long as the my commits remain intact.

**Pull request merged**
