### PR TITLE
v11.1.0

### PR DESCRIPTION
**Pull request by h-vetinari**
Continues & closes #114.

GCC 9 seems to cause some
<details>
<summary>problems...</summary>

```
[ 85%] Linking CXX static library ../../../../lib/libLLVMExegesisX86.a
[ 85%] Built target LLVMExegesisX86
../../lib/libLLVMXCoreCodeGen.a(XCoreLowerThreadLocal.cpp.o): in function `replaceConstantExprOp(llvm::ConstantExpr*, llvm::Pass*)':
XCoreLowerThreadLocal.cpp:(.text._ZL21replaceConstantExprOpPN4llvm12ConstantExprEPNS_4PassE+0x100): relocation truncated to fit: R_PPC64_REL24 against symbol `llvm::SmallVectorTemplateBase<llvm::WeakTrackingVH, false>::grow(unsigned long)' defined in .text._ZN4llvm23SmallVectorTemplateBaseINS_14WeakTrackingVHELb0EE4growEm[_ZN4llvm23SmallVectorTemplateBaseINS_14WeakTrackingVHELb0EE4growEm] section in ../../lib/libLLVMCodeGen.a(CodeGenPrepare.cpp.o)
../../lib/libLLVMXCoreCodeGen.a(XCoreLowerThreadLocal.cpp.o): in function `(anonymous namespace)::XCoreLowerThreadLocal::runOnModule(llvm::Module&)':
XCoreLowerThreadLocal.cpp:(.text._ZN12_GLOBAL__N_121XCoreLowerThreadLocal11runOnModuleERN4llvm6ModuleE+0x1284): relocation truncated to fit: R_PPC64_REL24 against symbol `llvm::SmallVectorTemplateBase<llvm::WeakTrackingVH, false>::grow(unsigned long)' defined in .text._ZN4llvm23SmallVectorTemplateBaseINS_14WeakTrackingVHELb0EE4growEm[_ZN4llvm23SmallVectorTemplateBaseINS_14WeakTrackingVHELb0EE4growEm] section in ../../lib/libLLVMCodeGen.a(CodeGenPrepare.cpp.o)
../../lib/libLLVMObject.a(WasmObjectFile.cpp.o): in function `llvm::object::WasmObjectFile::parseLinkingSectionSymtab(llvm::object::WasmObjectFile::ReadContext&)':
WasmObjectFile.cpp:(.text._ZN4llvm6object14WasmObjectFile25parseLinkingSectionSymtabERNS1_11ReadContextE+0x3e4): relocation truncated to fit: R_PPC64_REL24 against symbol `llvm::StringMapIterBase<llvm::StringMapIterator<llvm::NoneType>, llvm::StringMapEntry<llvm::NoneType> >::StringMapIterBase(llvm::StringMapEntryBase**, bool)' defined in .text._ZN4llvm17StringMapIterBaseINS_17StringMapIteratorINS_8NoneTypeEEENS_14StringMapEntryIS2_EEEC2EPPNS_18StringMapEntryBaseEb[_ZN4llvm17StringMapIterBaseINS_17StringMapIteratorINS_8NoneTypeEEENS_14StringMapEntryIS2_EEEC5EPPNS_18StringMapEntryBaseEb] section in ../../lib/libLLVMSupport.a(FileCheck.cpp.o)
WasmObjectFile.cpp:(.text._ZN4llvm6object14WasmObjectFile25parseLinkingSectionSymtabERNS1_11ReadContextE+0x9cc): relocation truncated to fit: R_PPC64_REL24 against symbol `llvm::StringMapIterBase<llvm::StringMapIterator<llvm::NoneType>, llvm::StringMapEntry<llvm::NoneType> >::StringMapIterBase(llvm::StringMapEntryBase**, bool)' defined in .text._ZN4llvm17StringMapIterBaseINS_17StringMapIteratorINS_8NoneTypeEEENS_14StringMapEntryIS2_EEEC2EPPNS_18StringMapEntryBaseEb[_ZN4llvm17StringMapIterBaseINS_17StringMapIteratorINS_8NoneTypeEEENS_14StringMapEntryIS2_EEEC5EPPNS_18StringMapEntryBaseEb] section in ../../lib/libLLVMSupport.a(FileCheck.cpp.o)
../../lib/libLLVMObject.a(WasmObjectFile.cpp.o): in function `llvm::object::WasmObjectFile::parseLinkingSectionComdat(llvm::object::WasmObjectFile::ReadContext&)':
WasmObjectFile.cpp:(.text._ZN4llvm6object14WasmObjectFile25parseLinkingSectionComdatERNS1_11ReadContextE+0x148): relocation truncated to fit: R_PPC64_REL24 against symbol `llvm::StringMapIterBase<llvm::StringMapIterator<llvm::NoneType>, llvm::StringMapEntry<llvm::NoneType> >::StringMapIterBase(llvm::StringMapEntryBase**, bool)' defined in .text._ZN4llvm17StringMapIterBaseINS_17StringMapIteratorINS_8NoneTypeEEENS_14StringMapEntryIS2_EEEC2EPPNS_18StringMapEntryBaseEb[_ZN4llvm17StringMapIterBaseINS_17StringMapIteratorINS_8NoneTypeEEENS_14StringMapEntryIS2_EEEC5EPPNS_18StringMapEntryBaseEb] section in ../../lib/libLLVMSupport.a(FileCheck.cpp.o)
WasmObjectFile.cpp:(.text._ZN4llvm6object14WasmObjectFile25parseLinkingSectionComdatERNS1_11ReadContextE+0x214): relocation truncated to fit: R_PPC64_REL24 against symbol `llvm::StringMapIterBase<llvm::StringMapIterator<llvm::NoneType>, llvm::StringMapEntry<llvm::NoneType> >::StringMapIterBase(llvm::StringMapEntryBase**, bool)' defined in .text._ZN4llvm17StringMapIterBaseINS_17StringMapIteratorINS_8NoneTypeEEENS_14StringMapEntryIS2_EEEC2EPPNS_18StringMapEntryBaseEb[_ZN4llvm17StringMapIterBaseINS_17StringMapIteratorINS_8NoneTypeEEENS_14StringMapEntryIS2_EEEC5EPPNS_18StringMapEntryBaseEb] section in ../../lib/libLLVMSupport.a(FileCheck.cpp.o)
../../lib/libLLVMObject.a(XCOFFObjectFile.cpp.o): in function `llvm::object::XCOFFObjectFile::relocations(llvm::object::XCOFFSectionHeader32 const&) const':
XCOFFObjectFile.cpp:(.text._ZNK4llvm6object15XCOFFObjectFile11relocationsERKNS0_20XCOFFSectionHeader32E+0xa8): relocation truncated to fit: R_PPC64_REL24 against symbol `llvm::Expected<unsigned int>::~Expected()' defined in .text._ZN4llvm8ExpectedIjED2Ev[_ZN4llvm8ExpectedIjED5Ev] section in ../../lib/libLLVMSupport.a(MemoryBuffer.cpp.o)
../../lib/libLLVMObject.a(XCOFFObjectFile.cpp.o): in function `llvm::object::XCOFFObjectFile::parseStringTable(llvm::object::XCOFFObjectFile const*, unsigned long)':
XCOFFObjectFile.cpp:(.text._ZN4llvm6object15XCOFFObjectFile16parseStringTableEPKS1_m+0xc4): relocation truncated to fit: R_PPC64_REL24 against symbol `llvm::Error llvm::handleErrors<llvm::consumeError(llvm::Error)::{lambda(llvm::ErrorInfoBase const&)#1}>(llvm::Error, llvm::consumeError(llvm::Error)::{lambda(llvm::ErrorInfoBase const&)#1}&&)' defined in .text._ZN4llvm12handleErrorsIJZNS_12consumeErrorENS_5ErrorEEUlRKNS_13ErrorInfoBaseEE_EEES1_S1_DpOT_[_ZN4llvm12handleErrorsIJZNS_12consumeErrorENS_5ErrorEEUlRKNS_13ErrorInfoBaseEE_EEES1_S1_DpOT_] section in ../../lib/libLLVMSupport.a(APFloat.cpp.o)
XCOFFObjectFile.cpp:(.text._ZN4llvm6object15XCOFFObjectFile16parseStringTableEPKS1_m+0x264): relocation truncated to fit: R_PPC64_REL24 against symbol `llvm::Expected<char const*>::~Expected()' defined in .text._ZN4llvm8ExpectedIPKcED2Ev[_ZN4llvm8ExpectedIPKcED5Ev] section in ../../lib/libLLVMSupport.a(APFloat.cpp.o)
../../lib/libLLVMDebugInfoCodeView.a(LazyRandomTypeCollection.cpp.o): in function `llvm::codeview::LazyRandomTypeCollection::reset(llvm::BinaryStreamReader&, unsigned int)':
LazyRandomTypeCollection.cpp:(.text._ZN4llvm8codeview24LazyRandomTypeCollection5resetERNS_18BinaryStreamReaderEj+0x21c): relocation truncated to fit: R_PPC64_REL24 against symbol `llvm::Error llvm::handleErrors<llvm::consumeError(llvm::Error)::{lambda(llvm::ErrorInfoBase const&)#1}>(llvm::Error, llvm::consumeError(llvm::Error)::{lambda(llvm::ErrorInfoBase const&)#1}&&)' defined in .text._ZN4llvm12handleErrorsIJZNS_12consumeErrorENS_5ErrorEEUlRKNS_13ErrorInfoBaseEE_EEES1_S1_DpOT_[_ZN4llvm12handleErrorsIJZNS_12consumeErrorENS_5ErrorEEUlRKNS_13ErrorInfoBaseEE_EEES1_S1_DpOT_] section in ../../lib/libLLVMSupport.a(APFloat.cpp.o)
../../lib/libLLVMDebugInfoCodeView.a(LazyRandomTypeCollection.cpp.o): in function `llvm::VarStreamArrayIterator<llvm::codeview::CVRecord<llvm::codeview::TypeLeafKind>, llvm::VarStreamArrayExtractor<llvm::codeview::CVRecord<llvm::codeview::TypeLeafKind> > >::VarStreamArrayIterator(llvm::VarStreamArray<llvm::codeview::CVRecord<llvm::codeview::TypeLeafKind>, llvm::VarStreamArrayExtractor<llvm::codeview::CVRecord<llvm::codeview::TypeLeafKind> > > const&, llvm::VarStreamArrayExtractor<llvm::codeview::CVRecord<llvm::codeview::TypeLeafKind> > const&, unsigned int, bool*)':
LazyRandomTypeCollection.cpp:(.text._ZN4llvm22VarStreamArrayIteratorINS_8codeview8CVRecordINS1_12TypeLeafKindEEENS_23VarStreamArrayExtractorIS4_EEEC2ERKNS_14VarStreamArrayIS4_S6_EERKS6_jPb[_ZN4llvm22VarStreamArrayIteratorINS_8codeview8CVRecordINS1_12TypeLeafKindEEENS_23VarStreamArrayExtractorIS4_EEEC5ERKNS_14VarStreamArrayIS4_S6_EERKS6_jPb]+0x4d4): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status
make[2]: *** [tools/llvm-shlib/CMakeFiles/LLVM.dir/build.make:299: lib/libLLVM-11.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:30031: tools/llvm-shlib/CMakeFiles/LLVM.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
```
</details>

Next step is trying to undo the compiler bump on ppc64le that #114 did.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Ok, those last two commits might have been unnecessary (strictly speaking), because this seems to be hanging on https://github.com/conda-forge/libcxx-feedstock/pull/73 on the one hand, but then the pinning for that probably should take into account the minor version as well...

**Comment by h-vetinari** [comment]
@isuruf 
This is just failing on the libname (`libLLVM-11.{so,dylib}` vs. `libLLVM-11.1.{so,dylib}`). How was this solved for previous `x.1` LLVM releases?

**Comment by isuruf** [comment]
> This is just failing on the libname (libLLVM-11.{so,dylib} vs. libLLVM-11.1.{so,dylib}). How was this solved for previous x.1 LLVM releases?

You answered it yourself in your previous comment.

> Ok, those last two commits might have been unnecessary (strictly speaking)

**Comment by h-vetinari** [comment]
Well, fair enough, but the build had failed (and I suspected it had something to do with the `.1` minor).

If not by absorbing the minor version, how do we unblock `11.1`, or are you planning to just not build it (12 is a couple weeks away I guess)?

**Comment by isuruf** [comment]
llvm 11.0 and 11.1 are compatible with each other. So, `libllvm11=11.1.0` is fine. You don't need `libllvm11.1=11.1.0`

**Comment by h-vetinari** [comment]
> 
> 
> llvm 11.0 and 11.1 are compatible with each other. So, `libllvm11=11.1.0` is fine. You don't need `libllvm11.1=11.1.0`

I get that, but conda build doesn't (though that's probably also partially due to the circular dependency that I mentioned above).

**Comment by isuruf** [comment]
For the osx error, we probably need to add a `ignore_run_exports_from` line to https://github.com/conda-forge/clang-compiler-activation-feedstock/blob/master/recipe/meta.yaml#L80

**Comment by h-vetinari** [comment]
@isuruf
This is now green - good analysis about which run-exports were causing the issue!

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
