### PR TITLE
5.x: Hide llvm symbols

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

When using [`root`](https://github.com/conda-forge/root-feedstock.git) in https://github.com/conda-forge/root-feedstock/pull/26 with RHEL7-like systems there is an error when OpenGL is loaded:

```
: CommandLine Error: Option 'help-list' registered more than once!
terminate called after throwing an instance of 'std::runtime_error'
  what():  >>> Interpreter compilation error:
inconsistency in registered CommandLine options
```

This is caused by LLVM being used by both OpenGL and ROOT. This PR avoid this conflict by building LLVM with `-fvisibility=hidden`. This has also been seen elsewhere (see https://github.com/symengine/symengine/issues/1473).

I've also included a couple of cosmetic changes that were needed to get conda-smithy to rerender the feedstock correctly.

### CODE REVIEW

**Comment by chrisburr** [comment]
I think the Windows failure isn't an issue as Appveyor is still being used.

@conda-forge/llvmdev This is ready to review.

**Comment by isuruf** [comment]
I don't think this is a good solution for all use cases. Why not do `-Wl,--exclude-libs,ALL` in root?

**Comment by chrisburr** [comment]
@isuruf Thanks for the pointer, that seems like a better solution.

Do you have any idea how I can specify how to only hide LLVM's symbols instead of `ALL`? Cling's symbols need to still be exposed and [ROOT's current way of doing this is to remove `-fvisibility=hidden` after building LLVM and Clang](https://github.com/root-project/root/commit/423b31a13ab71091b4e9775b17c864508ea29a81).

**Comment by isuruf** [comment]
> Do you have any idea how I can specify how to only hide LLVM's symbols instead of ALL? 

`-Wl,--exclude-libs,libLLVMTarget.a`

**Comment by chrisburr** [comment]
Perfect, thank you so much! I'll close this now.

**Pull request closed without merging**
