### PR TITLE
Rebuild 5.x with new compiler infrastructure

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@SylvainCorlay, when you are making new branches in the main repo to PR against, please make sure to cancel CI on them as they have been tested before.

**Comment by SylvainCorlay** [comment]
> @SylvainCorlay, when you are making new branches in the main repo to PR against, please make sure to cancel CI on them as they have been tested before.

Sorry about that and thanks for the heads up!

**Comment by SylvainCorlay** [comment]
Unfortunately the `noarch/llvm-meta-5.0.0-0.tar.bz2` has is not available for the gcc7 channel. (6.0.1 and 7.0 are there though).

@conda-forge/core would it be possible to label `llvm-meta` 5.0.0 and 6.0.0 with the `gcc7` tag manually? It is merely a meta package so I don't think that there should be any change.

**Comment by isuruf** [comment]
Done

**Comment by SylvainCorlay** [comment]
Thank!

**Comment by SylvainCorlay** [comment]
It looks like the appveyor build was interupted at one hour.

**Comment by SylvainCorlay** [comment]
`Build exceeded allowed resource quotas. Fix your build to consume less resources or contact AppVeyor support to request quotas increase.`

**Comment by mingwandroid** [comment]
You may be able to get away with -j1 instead of -j${CPU_COUNT} or maybe ask AppVeyor as suggested.

Anyway, shouldn't we consider a move to Azure Pipelines? 6 hours build time, 10 cores, all 3 OSes (though Python 2.7 will require some jerry-rigging!).

**Comment by SylvainCorlay** [comment]
> You may be able to get away with -j1 instead of -j${CPU_COUNT} or maybe ask AppVeyor as suggested.

Thanks. Trying that out.

> Anyway, shouldn't we consider a move to Azure Pipelines? 6 hours build time, 10 cores, all 3 OSes (though Python 2.7 will require some jerry-rigging!).

I am a bit wary of Microsoft offering these free services that will be basically kill the competition right after the acquisition of GitHub. (Selling at a loss is actually generally illegal in the EU, which is meant to prevent dominant actors on a market from killing emerging competitors.)

**Comment by dougalsutherland** [comment]
@mingwandroid @SylvainCorlay, Azure Pipelines support is being worked on in https://github.com/conda-forge/conda-smithy/pull/901, FYI.

**Comment by SylvainCorlay** [comment]
cc @scopatz do you know how to enable the 90minutes build time on appveyor?

**Comment by jakirkham** [comment]
For future reference I've normally just asked for it to bumped particularly for the LLVM stack, which has long build times. They've been pretty helpful. Here's the AppVeyor build limit issue for `llvmdev` specifically should you need it again. ( https://github.com/appveyor/ci/issues/2555 )

**Pull request merged**
