### PR TITLE
Do not merge: Apply upstream aarch64 consecutive register fix (11.x)

### PR DESCRIPTION
**Pull request by hmaarrfk**
Closes #164

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Review by isuruf — CHANGES_REQUESTED** [review]
This is an ABI breakage. See the last comment in https://bugs.llvm.org/show_bug.cgi?id=46996

**Comment by hmaarrfk** [comment]
Thank you for pointing this out. I'm going to let this run, to see if holding back the compiler helps osx for educational purposes.

**Comment by hmaarrfk** [comment]
Seems like OSX didn't get fixed from this.

**Comment by gmarkall** [comment]
> This is an ABI breakage. See the last comment in https://bugs.llvm.org/show_bug.cgi?id=46996

Isn't that only the case when the LLVM 12-specific version of the patch is applied to LLVM 12? It looks like the version applied to the LLVM 11 branch was OK: https://bugs.llvm.org/show_bug.cgi?id=46996#c9

**Comment by isuruf** [comment]
Why do you think it's not an ABI breakage for LLVM 11? The patch for LLVM 11 changes the signature for a public method which changes the name mangling and therefore is an ABI breakage

**Comment by gmarkall** [comment]
> Why do you think it's not an ABI breakage for LLVM 11? The patch for LLVM 11 changes the signature for a public method which changes the name mangling and therefore is an ABI breakage

Thanks for the clarification, I was wrong about this. I'd misunderstood some of the discussion on the LLVM bug which lead me to believe that the ABI was the same for LLVM 11 but differed for LLVM 12.

**Pull request closed without merging**
